name: Mirror to Codeberg
on:
  push:
    branches:
      - '**'
  delete:
  create:
  schedule:
   - cron: '0 */5 * * *'  # Runs every 5 hours (at minute 0)
  workflow_dispatch:

permissions:
  contents: read

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -t ed25519 github.com codeberg.org > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push to Codeberg
        run: |
          git remote add codeberg ${{ vars.CODEBERG_REPO }}
          git push --force codeberg --all || { echo "Failed to push branches to Codeberg"; exit 1; }
          git push --force codeberg --tags || { echo "Failed to push tags to Codeberg"; exit 1; }
