name: Mirror to Codeberg
on:
  push:
    branches:
      - '**'
  delete:
  create:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          # Create SSH directory and set permissions
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Write private key
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          # Write known hosts with current correct keys
          echo "github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl" > ~/.ssh/known_hosts
          # Updated Codeberg.org key matching the SHA256:mIlxA9k46MmM6qdJOdMnAQpzGxF4WIVVL+fj+wZbw0g fingerprint
          echo "codeberg.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJwZit/5Vv0HNyQBXtmYIMaC9HJzGKzYPicQGNpLX+Ir" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

          # Configure git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push to Codeberg
        run: |
          # Add Codeberg as remote
          git remote add codeberg git@codeberg.org:xxshade/windows-telemetry-blocklist.git

          # Push all branches and tags
          git push --force codeberg --all
          git push --force codeberg --tags
